export declare const API_BASE = "https://api.rendex.dev";
export declare const CREDENTIAL_TEST_PATH = "/v1/credential-check";
export declare const SCREENSHOT_ENDPOINT = "/v1/screenshot";
export declare const SCREENSHOT_JSON_ENDPOINT = "/v1/screenshot/json";
export declare const BATCH_ENDPOINT = "/v1/screenshot/batch";
export declare const EXTRACT_ENDPOINT = "/v1/extract";
export declare const JOBS_ENDPOINT = "/v1/jobs";
export declare const BATCHES_ENDPOINT = "/v1/batches";
export declare const WATCHES_ENDPOINT = "/v1/watches";
//# sourceMappingURL=constants.d.ts.map